services:
  - type: web
    name: tennis-match-scoreboard
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: mvn clean package
    startCommand: catalina.sh run
    envVars:
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: your-db-name
      - key: DB_USER
        value: your-db-user
      - key: DB_PASSWORD
        value: your-db-password
    runtime: docker
